name: dash

on:
  pull_request

jobs:
  check-dash:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create Dash Dependency Report
        run: ./gradlew mergeDashFiles

      - name: Dash license check
        uses: eclipse-kuksa/kuksa-actions/check-dash@2
        with:
          dashinput: ${{github.workspace}}/build/oss/all/all-dependencies.txt
